POST http://localhost:3000/api/events
Content-Type: application/json

{
    "name": "evento de prueba 2",
    "description": "prueba 321",
    "fecha_evento": "2025-10-10",
    "hora_evento": "22:30",
    "usuarios_id": 1
}