POST http://localhost:3000/api/guest
Content-Type: application/json


    {
        "guest_name": "Maria jose",
        "events_id": 1,
        "guest_email": "kelvinchirinos485@gmail.com",
        "indications": ""
    }
    
